SAWorkplace/Controllers/AllocationController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SAWorkplace.Data;
using SAWorkplace.Models;
using SAWorkplace.Helpers;
using SAWorkplace.Constants;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.AspNetCore.SignalR;
using LoggerService;

namespace SAWorkplace.Controllers
{
    public class AllocationController : Controller
    {
        protected ApplicationDBContext aContext;
        private readonly IConfiguration _config;
        protected EmailHelper eHelper;
        private static ILoggerManager _logger;
        public AllocationController(ApplicationDBContext context, IConfiguration configuration, ILoggerManager logger)
        {
            aContext = context;
            _config = configuration;
            _logger = logger;
            eHelper = new EmailHelper(context, configuration, logger);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string viewType)
        {
            _logger.LogInfo("Starting Get Allocation Index.");
  
            string PSArchitect = HttpContext.Session.GetString("PSArchitect");
            string ECUser = HttpContext.Session.GetString("ECUser");
            string AdminUser = HttpContext.Session.GetString("AdminUser");
            string userId = HttpContext.Session.GetString("UserID");

            if (string.IsNullOrEmpty(viewType))
            {
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("ViewType")))
                {
                    viewType = HttpContext.Session.GetString("ViewType");
                }
                else
                {
                    if (ECUser == "True")
                        viewType = "EC";
                    else if (AdminUser == "True")
                        viewType = "Admin";
                    else
                        viewType = "User";
                }
            }
            else
            {
                HttpContext.Session.SetString("FilterType", "");
            }

            HttpContext.Session.SetString("ViewType", viewType);
            HttpContext.Session.SetString("SearchText", "");

            _logger.LogDebug("PSArchitect = " + PSArchitect + ", userId = " + userId + ", viewType = " + viewType);

            var sortType = "SORT:RequestDate_new";
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("SortType")))
            {
                sortType = HttpContext.Session.GetString("SortType");
            }
            else 
            { 
                HttpContext.Session.SetString("SortType", sortType); 
            }

            DataAccess data = new DataAccess(aContext, HttpContext.Session);
            RequestDisplayModel requestDisplay = new RequestDisplayModel();

            var filterType = "Open";
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("FilterType")))
            {
                filterType = HttpContext.Session.GetString("FilterType");
            }
            else
            {
                HttpContext.Session.SetString("FilterType", filterType);
            }

            string areas = HttpContext.Session.GetString("SMEAreas");

            requestDisplay.Requests = data.LoadRequests(userId, 0, PSArchitect, "", filterType, sortType, "", areas);

            requestDisplay.Carriers = await data.LoadActiveCarriers();
            requestDisplay.Status = await data.GetStatuses();
            requestDisplay.Progress = await data.GetProgress();
            requestDisplay.RequestTypes = await data.GetRequestTypes();
            requestDisplay.DurationTypes = await data.GetDurationTypes();
            return View("Index", requestDisplay);
        }

        [Route("Allocation/Chart")]
        public async Task<IActionResult> Requests(string filterType)
        {
            //_logger.LogDebug("Starting Get Requests: filterType = " + filterType + ", sortType = " + sortType);

            DataAccess data = new DataAccess(aContext, HttpContext.Session);
            string PSArchitect = HttpContext.Session.GetString("PSArchitect");
            string userId = HttpContext.Session.GetString("UserID");
            string viewType = HttpContext.Session.GetString("ViewType");
            if (viewType != "Admin")
            {
                PSArchitect = "False";
                HttpContext.Session.SetString("FilterType", "");
            }

            if (!string.IsNullOrEmpty(filterType))
            {
                HttpContext.Session.SetString("FilterType", filterType);
                HttpContext.Session.SetString("SearchText", "");
            }
            else
            {
                if (string.IsNullOrEmpty(filterType) && !string.IsNullOrEmpty(HttpContext.Session.GetString("FilterType")))
                    filterType = HttpContext.Session.GetString("FilterType");
            }

            string areas = HttpContext.Session.GetString("SMEAreas");

            RequestDisplayModel requestDisplay = new RequestDisplayModel();
            requestDisplay.Requests = data.LoadRequests(userId, 0, PSArchitect, "", filterType, "", "", areas);

            requestDisplay.Carriers = await data.LoadActiveCarriers();
            requestDisplay.Status = await data.GetStatuses();
            requestDisplay.Progress = await data.GetProgress();
            requestDisplay.RequestTypes = await data.GetRequestTypes();
            requestDisplay.DurationTypes = await data.GetDurationTypes();
            return PartialView("/Views/Partial/Charts.cshtml", requestDisplay);
        }
  
    }
}

SAWorkplace/Views/Allocation/Index.cshtml
@using Microsoft.AspNetCore.Http;
@using System.Security.Claims;
<script type="text/javascript">
    $(function () {
        $(".filters").click(function () {
            var filterType = $(this).attr("id");
            var formData = new FormData();
            formData.append("filterType", filterType);
            var action = '@(Url.Action("Chart", "Allocation"))';

            $.ajax({
                url: action,
                type: "POST",
                data: formData,
                processData: false,
                contentType: false,
                dataType: 'text',
                error: function (data) {

                },
                success: function (data) {
                    $("#chartContainer").html(data);
                }
            });
        });
    });
    $(document).ready(function () {
        $('.ui.dropdown').dropdown({"clearable": true});
        $(".se-pre-con").fadeOut("slow");

        $('#requestTop').removeClass('active');
        $('#allocationTop').addClass('active');
    });
</script>

<div id="allocHeader" class="ui container-fluid" style="padding:17px 5px 5px 5px">
    <div class="ui grid">
        <div class="ui two wide column">
            <h1 id="h2Request">Allocation</h1>
        </div>

        @{
            string viewType = Context.Session.GetString("ViewType");

            if (viewType != "User")
            {
                <div class="ui three wide column right bottom aligned">
                    <div class="ui dropdown">

                        @{string filterType = Context.Session.GetString("FilterType");

                            if (string.IsNullOrEmpty(filterType))
                            {
                                filterType = "Filter";
                            }
                            else if (filterType == "Open")
                            {
                                filterType = "All Open Requests";
                            }
                            else if (filterType == "FeasOpen")
                            {
                                filterType = "Open Feasibility(Feas/Init/Impl) Reviews";
                            }
                            else if (filterType == "FeasAll")
                            {
                                filterType = "All Feasibility(Feas/Init/Impl) Reviews";
                            }
                            else
                            {
                                filterType += " Requests";
                            }

                            <div class="text">@filterType</div>
                        }
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a class="item filters" id="Open">All Open Requests</a>
                            <a class="item filters" id="All">All Requests</a>

                            @{
                                string PSArchitect = Context.Session.GetString("PSArchitect");

                                if (PSArchitect == "True" || viewType == "SME")
                                {
                                    <a class="item filters" id="My">My Requests</a>
                                    <a class="item filters" id="My Open">My Open Requests</a>
                                    <a class="item filters" id="My Pending">My Pending Requests</a>
                                    <a class="item filters" id="My Closed">My Closed Requests</a>
                                    if (viewType == "SME")
                                    {
                                        <a class="item filters" id="My Areas">My Area Requests</a>
                                    }
                                    if (PSArchitect == "True")
                                    {
                                        <a class="item filters" id="FeasOpen">Open Feasibility(Feas/Init/Impl) Reviews</a>
                                        <a class="item filters" id="FeasAll">All Feasibility(Feas/Init/Impl) Reviews</a>
                                    }

                                }
                                if (viewType == "Admin" || viewType == "EC")
                                {
                                    <a class="item filters" id="Open SME">Open SME Requests</a>
                                    <a class="item filters" id="All SME">All SME Requests</a>
                                    <a class="item filters" id="Steel Thread">Steel Thread Requests</a>
                                }
                                if (viewType == "EC")
                                {
                                    <a class="item filters" id="Staffing">Staffing Requests</a>
                                }
                                if (viewType != "Director")
                                {
                                    <a class="item filters" id="Unassigned">Unassigned Requests</a>
                                }
                            }
                        </div>
                    </div>
                </div>
            }

        }
        <br />

    </div>
</div>

@{ await Html.RenderPartialAsync("/Views/Partial/Charts.cshtml");}