SAWorkplace/Models/FeasibilityReviewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SAWorkplace.Models
{
    public class FeasibilityReviewModel
    {
        [Key]
        public int ID { get; set; }
        public int TicketNumber { get; set; }
        public string ProjectName { get; set; }
        public string TeamMembers { get; set; }

        public string Feas_ReviewedBy { get; set; }
        public string Feas_ReviewDate { get; set; }
        public string Feas_RequirePOC { get; set; }
        public string Feas_RequirePOCDetail { get; set; }
        public string Feas_IPProduct { get; set; }
        public string Feas_IPProductDetail { get; set; }
        public string Feas_Gaps { get; set; }
        public string Feas_GapsDetail { get; set; }
        public string Feas_OutsideService { get; set; }
        public string Feas_OutsideServiceDetail { get; set; }
        public string Feas_BestUX { get; set; }
        public string Feas_BestUXDetail { get; set; }
        public string Feas_StandardESig { get; set; }
        public string Feas_StandardESigDetail { get; set; }
        public string Feas_AdditionalCosts { get; set; }
        public string Feas_ItemsNeeded { get; set; }
        public string Feas_JIRAs { get; set; }
        public string Feas_Notes { get; set; }

        //Initiation Review
        public string Init_ReviewedBy { get; set; }
        public string Init_ReviewDate { get; set; }
        public string Init_Workflow { get; set; }
        public string Init_WorkflowDetail { get; set; }
        public string Init_POCResults { get; set; }
        public string Init_POCResultsDetail { get; set; }
        public string Init_IPProduct { get; set; }
        public string Init_IPProductDetail { get; set; }
        public string Init_Gaps { get; set; }
        public string Init_GapsDetail { get; set; }
        public string Init_IntegrationReq { get; set; }
        public string Init_IntegrationReqDetail { get; set; }
        public string Init_UX { get; set; }
        public string Init_UXDetail { get; set; }
        public string Init_AdditionalCosts { get; set; }
        public string Init_ItemsNeeded { get; set; }
        public string Init_JIRAs { get; set; }
        public string Init_Notes { get; set; }

        //Post Initial Build Review
        public string InitBuild_ReviewedBy { get; set; }
        public string InitBuild_ReviewDate { get; set; }
        public string InitBuild_Topology { get; set; }
        public string InitBuild_TopologyDetail { get; set; }
        public string InitBuild_Compliance { get; set; }
        public string InitBuild_ComplianceDetail { get; set; }
        public string InitBuild_Gaps { get; set; }
        public string InitBuild_GapsDetail { get; set; }
        public string InitBuild_IntegrationReq { get; set; }
        public string InitBuild_IntegrationReqDetail { get; set; }
        public string InitBuild_UX { get; set; }
        public string InitBuild_UXDetail { get; set; }
        public string InitBuild_AdditionalCosts { get; set; }
        public string InitBuild_ItemsNeeded { get; set; }
        public string InitBuild_JIRAs { get; set; }
        public string InitBuild_Notes { get; set; }

        //Implementation Review
        public string Impl_ReviewedBy { get; set; }
        public string Impl_ReviewDate { get; set; }
        public string Impl_Topology { get; set; }
        public string Impl_TopologyDetail { get; set; }
        public string Impl_Compliance { get; set; }
        public string Impl_ComplianceDetail { get; set; }
        public string Impl_Gaps { get; set; }
        public string Impl_GapsDetail { get; set; }
        public string Impl_IntegrationReq { get; set; }
        public string Impl_IntegrationReqDetail { get; set; }
        public string Impl_UX { get; set; }
        public string Impl_UXDetail { get; set; }
        public string Impl_AdditionalCosts { get; set; }
        public string Impl_ItemsNeeded { get; set; }
        public string Impl_JIRAs { get; set; }
        public string Impl_Notes { get; set; }

    }
}

SAWorkplace/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SAWorkplace.Data;
using SAWorkplace.Models;

namespace SAWorkplace.Controllers
{
    public class DocumentController : Controller
    {
        protected ApplicationDBContext dContext;
        public DocumentController(ApplicationDBContext context)
        {
            dContext = context;
        }

        [HttpGet]
        [Route("Document/DeleteDocument")]
        public async Task<IActionResult> DeleteDocument(int ticketNum, int requestType)
        {
            DataAccess data = new DataAccess(dContext, HttpContext.Session);
            RequestEditModel requestEdit = new RequestEditModel();
            requestEdit.Requests = data.LoadRequest(Convert.ToInt32(ticketNum));

            var requestStatus = requestEdit.Requests.RequestStatus;
            //don't delete if the request is closed
            if (requestStatus == 3 || requestStatus == 4 || requestStatus == 10 || requestStatus == 15)
            {
                return Json(new { success = false, responseType = "Document", responseText = "Document cannot be deleted" });
            }

            return Json(new { success = true, responseType = "Document", responseText = "Document can be deleted" });
        }
        [HttpPost]
        [Route("Document/DeleteDocument")]
        public async Task<IActionResult> DeleteDocument(int documentID, int ticketNum, int requestType)
        {
            var delDocument = dContext.tblDocuments.Find(documentID);
            dContext.tblDocuments.Remove(delDocument);
            dContext.SaveChanges();

            DataAccess data = new DataAccess(dContext, HttpContext.Session);
            DocumentDisplayModel documentModel = new DocumentDisplayModel();
            documentModel.Documents = await data.LoadDocuments(ticketNum);
            documentModel.TicketNumber = ticketNum;
            documentModel.RequestType = requestType;

            return PartialView("/Views/Partial/Documents.cshtml",documentModel); 

            //return Json(new { success = true, responseType = "Document", responseText = "Document Deleted" });
        }

        [HttpGet]
        [Route("Document/AddDocument")]
        public IActionResult AddDocument(int ticketNum)
        {

            return PartialView("/Views/Modal/AddDocument.cshtml", ticketNum);
        }

        [HttpPost]
        [Route("Document/AddDocument")]
        public async Task<IActionResult> AddDocument([FromServices]ApplicationDBContext context, int ticketNum, int requestType, string documentType, IFormFile Document)
        {
            var DocName = "";
            var DocType = "";
            var DocExt = "";
            var DocModifiedBy = "";
            DateTime DocModifiedDate;
            var DocDirectory = "";
            string userName = HttpContext.Session.GetString("UserName");

            var path = Path.Combine(Directory.GetCurrentDirectory(), "Documents\\" + ticketNum);

            System.IO.Directory.CreateDirectory(path + "\\" + documentType.Replace(" ", "_"));
            DocDirectory = "Documents/" + ticketNum + "/" + documentType.Replace(" ", "_");
            string SavedDocName = Document.FileName.Replace(" ", "_");
            string QFullName = Path.Combine(DocDirectory, SavedDocName);
            using (FileStream stream = new FileStream(QFullName, FileMode.Create))
            {
                await Document.CopyToAsync(stream);
            }

            DocName = Document.FileName.Replace(" ", "_"); ;
            DocType = documentType;
            DocExt = Path.GetExtension(Document.FileName).Replace(".", "");
            DocModifiedBy = userName;
            DocModifiedDate = DateTime.Now;

            context.Add(new DocumentModel
            {
                DocumentName = DocName,
                DocumentModifiedByName = DocModifiedBy,
                DocumentExt = DocExt,
                DocumentModifiedDate = DocModifiedDate,
                DocumentPath = DocDirectory,
                DocumentType = DocType,
                TicketNumber = ticketNum
            });
            context.SaveChanges();

            DataAccess data = new DataAccess(dContext, HttpContext.Session);
            DocumentDisplayModel documentModel = new DocumentDisplayModel();
            documentModel.Documents = await data.LoadDocuments(ticketNum);
            documentModel.TicketNumber = ticketNum;
            documentModel.RequestType = requestType;

            return PartialView("/Views/Partial/Documents.cshtml", documentModel);
        }
    }
}

SAWorkplace/Controllers/LoadTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SAWorkplace.Data;
using SAWorkplace.Models;

namespace SAWorkplace.Controllers
{
    public class LoadTestController : Controller
    {
        protected ApplicationDBContext dContext;
        private IHubContext<Services.SignalR_Notifications> _hubContext;

        public LoadTestController(ApplicationDBContext context)
        {
            dContext = context;
        }

        [HttpPost]
        [Route("LoadTest/DeleteLoadTest")]
        public async Task<IActionResult> DeleteLoadTest(int LoadTestID, int ticketNum, int carrierId)
        {
            var delLoadTest = dContext.tblLoadTestResults.Find(LoadTestID);
            dContext.tblLoadTestResults.Remove(delLoadTest);
            dContext.SaveChanges();

            //DataAccess data = new DataAccess(dContext);

            //RequestEditModel requestEdit = new RequestEditModel();
            //requestEdit.Requests = data.LoadRequest(Convert.ToInt32(ticketNum));
            //requestEdit.Documents = await data.LoadDocuments(ticketNum);
            //requestEdit.History = data.LoadHistory(ticketNum);
            //requestEdit.Carriers = await data.LoadSingleCarrier(carrierId);
            //requestEdit.LoadTestResults = await data.LoadTestResults(Convert.ToInt32(ticketNum));

            //string tempResults = "";

            //foreach(var result in requestEdit.LoadTestResults)
            //{
            //    tempResults = tempResults + "," + result.TestResult;

            //}

            //if(tempResults.Contains("Fail"))
            //{
            //    requestEdit.Requests.RequestStatus = 9;
            //}
            //else if(tempResults.Contains("Off"))
            //{
            //    requestEdit.Requests.RequestStatus = requestEdit.Requests.RequestStatus;
            //}
            //else
            //{
            //    requestEdit.Requests.RequestStatus = 10;
            //}

            //return PartialView("/Views/Modal/SAViews/LoadTest.cshtml", requestEdit);

            DataAccess data = new DataAccess(dContext, HttpContext.Session);
            LoadTestDisplayModel loadTestModel = new LoadTestDisplayModel();
            loadTestModel.LoadTests = await data.LoadTestResults(ticketNum);
            loadTestModel.TicketNumber = ticketNum;

            return PartialView("/Views/Partial/LoadTestResults.cshtml", loadTestModel);

        }

        [HttpGet]
        [Route("LoadTest/AddLoadTest")]
        public IActionResult AddLoadTest(int ticketNum, int carrierId)
        {
            LoadTestDisplayModel loadTestModel = new LoadTestDisplayModel();
            loadTestModel.TicketNumber = ticketNum;
            loadTestModel.CarrierID = carrierId;
            return PartialView("/Views/Modal/AddLoadTest.cshtml", loadTestModel);
        }

        [HttpPost]
        [Route("LoadTest/AddLoadTest")]
        public async Task<IActionResult> AddLoadTest([FromServices]ApplicationDBContext context, int ticketNum, int carrierId, string interfaceName, string reviewLTStatus, DateTime dcTestedTime, double Burst_Min, double Burst_Max, double Burst_Avg, double Variance_Min, double Variance_Max, double Variance_Avg,[FromServices]IHubContext<Services.SignalR_Notifications> hubContext)
        {
            _hubContext = hubContext;
            context.Add(new LoadTestModel
            {
                TicketNumber = ticketNum,
                InterfaceName = interfaceName,
                TestResult = reviewLTStatus,
                DateTested = dcTestedTime,
                Burst_Min = Burst_Min,
                Burst_Max = Burst_Max,
                Burst_Avg = Burst_Avg,
                Variance_Min = Variance_Min,
                Variance_Max = Variance_Max,
                Variance_Avg = Variance_Avg
            });
            context.SaveChanges();

            DataAccess data = new DataAccess(dContext, HttpContext.Session);

            LoadTestDisplayModel loadTestModel = new LoadTestDisplayModel();
            loadTestModel.LoadTests = await data.LoadTestResults(ticketNum);
            loadTestModel.TicketNumber = ticketNum;

            await _hubContext.Clients.All.SendAsync("Review_Added", ticketNum);

            return PartialView("/Views/Partial/LoadTestResults.cshtml", loadTestModel);
        }
    }
}

SAWorkplace/Views/Partial/Charts.cshtml
@model SAWorkplace.Models.RequestDisplayModel
@using Microsoft.AspNetCore.Http;

<script>
    $(document).ready(function () {
        $(".se-pre-con").fadeOut("slow");
    });
</script>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(drawChart1);

    function drawChart1() {

        //get number of tickets per Request Type
        var n1 = @Model.Requests.Where(x => x.RequestType == 1).Count(); //webservice code review
        var n2 = @Model.Requests.Where(x => x.RequestType == 2).Count(); //load test
        var n3 = @Model.Requests.Where(x => x.RequestType == 3).Count(); //project issue
        var n4 = @Model.Requests.Where(x => x.RequestType == 4).Count(); //Feasibility
        var n5 = @Model.Requests.Where(x => x.RequestType == 5).Count(); //concern
        var n6 = @Model.Requests.Where(x => x.RequestType == 6).Count(); //initiation
        var n7 = @Model.Requests.Where(x => x.RequestType == 7).Count(); //implementation
        var n100 = @Model.Requests.Where(x => x.RequestType == 100).Count(); //ACORD DD
        var n200 = @Model.Requests.Where(x => x.RequestType == 200).Count(); //AWS
        var n300 = @Model.Requests.Where(x => x.RequestType == 300).Count(); //Base
        var n400 = @Model.Requests.Where(x => x.RequestType == 400).Count(); //DevOps
        var n500 = @Model.Requests.Where(x => x.RequestType == 500).Count(); //DTC
        var n600 = @Model.Requests.Where(x => x.RequestType == 600).Count(); //eSig
        var n700 = @Model.Requests.Where(x => x.RequestType == 700).Count(); //Foundations Standards
        var n800 = @Model.Requests.Where(x => x.RequestType == 800).Count(); //Go No Go
        var n900 = @Model.Requests.Where(x => x.RequestType == 900).Count(); //JavaScript
        var n1000 = @Model.Requests.Where(x => x.RequestType == 1000).Count(); //Medical Vendors
        var n1100 = @Model.Requests.Where(x => x.RequestType == 1100).Count(); //NGSD
        var n1200 = @Model.Requests.Where(x => x.RequestType == 1200).Count(); //Security
        var n1300 = @Model.Requests.Where(x => x.RequestType == 1300).Count(); //UX
        var n1400 = @Model.Requests.Where(x => x.RequestType == 1400).Count(); //WS

        var data = google.visualization.arrayToDataTable([
            ['Requests', 'Type', 'Open Tickets'],
            ['WS Code Review', 1, n1],
            ['WS Load Test', 2, n2],
            ['Project Issue Support', 3, n3],
            ['Project Concern/Alert', 5, n5],
            ['Feasibility Review', 4, n4],
            ['Initiation Review', 6, n6],
            ['Implementation Review', 7, n7],
            ['ACORD/Data Dictionary', 100, n100],
            ['AWS', 200, n200],
            ['Base Issue/Question', 300, n300],
            ['DevOps', 400, n400],
            ['DTC', 500, n500],
            ['eSignature', 600, n600],
            ['Foundations/Standards', 700, n700],
            ['Go/No Go', 800, n800],
            ['JavaScript', 900, n900],
            ['Medical Vendor (MRAS, SwissRe, etc)', 1000, n1000],
            ['NGSD', 1100, n1100],
            ['Security', 1200, n1200],
            ['UI/UX', 1300, n1300],
            ['Web Services', 1400, n1400]
        ]);

        var view = new google.visualization.DataView(data);
        view.setColumns([0, 2]);

        var filterType = '@Context.Session.GetString("FilterType")';

        if (filterType.startsWith("Feas")) {
            if (filterType == "FeasOpen")
                filterType = "Open Feasibility";
            else
                filterType = "All Feasibility";
        }

        if (filterType != "") filterType += " ";

        console.log("filterType = " + filterType)

        var options = {
            title: filterType + 'Requests'
        };

        var chart = new google.visualization.PieChart(
            document.getElementById('chartRequests'));
        chart.draw(view, options);

        var selectHandler = function (e) {
            var type = data.getValue(chart.getSelection()[0]['row'], 1);
            top.location.href = '/Request?filter=rID_' + type;
        }
        google.visualization.events.addListener(chart, 'select', selectHandler);
    }
</script>

<script type="text/javascript">
    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(drawChart2);

    function drawChart2() {

        var data = new google.visualization.DataTable();

        data.addColumn('string', 'Status');
        data.addColumn('number', 'ID');
        data.addColumn('number', 'Requests');

        var a, b, c;

        @foreach (var d in Model.Status)
        {
            @:a = "@d.Text";
            @:b = @d.ID;
            @:c = @Model.Requests.Where(x => x.RequestStatus == d.ID).Count();

            @:data.addRows([[a, b, c]]);
        }

        var view = new google.visualization.DataView(data);
        view.setColumns([0, 2]);

        var filterType = '@Context.Session.GetString("FilterType")';
        if (filterType.startsWith("Feas")) {
            if (filterType == "FeasOpen")
                filterType = "Open Feasibility";
            else
                filterType = "All Feasibility";
        }
        if (filterType != "") filterType += " ";

        var options = {
            title: filterType + 'Statuses'
        };

        var chart = new google.visualization.PieChart(
            document.getElementById('chartStatus'));
        chart.draw(view, options);

        var selectHandler = function (e) {
            var type = data.getValue(chart.getSelection()[0]['row'], 1);
            top.location.href = '/Request?filter=sID_' + type;
        }

        google.visualization.events.addListener(chart, 'select', selectHandler);
    }
</script>

<script type="text/javascript">
    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(drawChart3);

    function drawChart3() {

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Carrier');
        data.addColumn('number', 'ID');
        data.addColumn('number', 'Requests');

        var emptyData = new google.visualization.DataTable();
        emptyData.addColumn('string', 'Carrier');
        emptyData.addColumn('number', 'ID');
        emptyData.addColumn('number', 'Requests');
        //emptyData.addRows([[" ", 0, -1]]);

        var a, b, c;

        @foreach (var d in Model.Carriers)
        {
            @:a = "@d.CarrierName";
            @:b = @d.CarrierId;
            @:c = @Model.Requests.Where(x => x.CarrierId == d.ID).Count();

            @:a = a.replace("&amp;", "&");

            @:if (c === 0)
                @:emptyData.addRows([[a, b, 1]]);
            @:else
                @:data.addRows([[a, b, c]]);
        }

        //emptyData.addRows([[" ", 999, 1]]);


        var view = new google.visualization.DataView(data);
        //view.setColumns([0, 2]);
        view.setColumns([0, 2,
            {
                calc: "stringify",
                sourceColumn: 2,
                type: "string",
                role: "annotation"
            }
          ]);

        var filter = '@Context.Session.GetString("FilterType")';

        var filterText = filter.trim();

        if (filter != "") filterText += " ";

        var chart_title = "Carriers";

        if (filter.trim() == "All")
            chart_title = "All Carriers with Requests";
        else
            chart_title = "Carriers with " + filterText + "Requests";

        if (filter.startsWith("My")) {
            chart_title = "My Carriers with " + filterText.replace("My ","") + "Requests";
        }

        if (filter.startsWith("Feas")) {
            if (filter.trim() == "FeasOpen") {
                filterText = "Open Feasibility Reviews";
                chart_title = "Carriers with " + filterText;
            }
            else {
                filterText = "Feasibility Reviews";
                chart_title = "All Carriers with " + filterText;
            }
        }

        var options = {
            title: chart_title,
            height: 1400,
            width: 900,
            bar: { groupWidth: "75%" },
        };

        var chart = new google.visualization.BarChart(
            document.getElementById('chartCarrier'));
        chart.draw(view, options);

        var selectHandler = function (e) {
            var type = data.getValue(chart.getSelection()[0]['row'], 1);
            top.location.href = '/Request?filter=carrierID_' + type;
        }
        google.visualization.events.addListener(chart, 'select', selectHandler);


        var viewType = '@Context.Session.GetString("ViewType")';
        if ((viewType == "Admin" || viewType == "EC") && (filter == "Open" || filter == "All" || filter.startsWith("Feas"))) 
        {
            var emptyView = new google.visualization.DataView(emptyData);
            emptyView.setColumns([0, 2]);

            var echart_title = "Carriers with Zero Requests";
            if (filter == "Open")
                echart_title = "Carriers with Zero Open Requests";
            else if (filter.startsWith("Feas"))
                echart_title = "Carriers with Zero " + filterText;

            var emptyOptions = {
                title: echart_title,
                pieSliceText: 'label',
            };

            var emptyChart = new google.visualization.PieChart(
                document.getElementById('chartEmpty'));
            emptyChart.draw(emptyView, emptyOptions);
        }
    }
</script>

<div class="se-pre-con"><div style="text-align:center; vertical-align:middle"><br /><br /><br /><br /><h1>Loading Allocation...</h1><br /><img src="~/img/indicators/loading.gif" /></div></div>
<div id="chartContainer">
    <hr />
    <div class="ui grid">
        <div class="ui eight wide column">
            <div id="chartRequests" style="width: 900px; height: 500px;"></div>
        </div>
        <div class="ui eight wide column">
            <div id="chartStatus" style="width: 900px; height: 500px;"></div>
        </div>
        <div class="ui eight wide column">
            <div id="chartCarrier" style="width: 900px; height: 1400px;"></div>
        </div>
        <div class="ui eight wide column">
            <div id="chartEmpty" style="width: 900px; height: 800px;"></div>
        </div>
    </div>
</div>

SAWorkplace/Views/Partial/LoadTestResults.cshtml
@model SAWorkplace.Models.LoadTestDisplayModel
@using Microsoft.AspNetCore.Http;

<script>
    function AddLoadTest(ticketNum, CarrierID) {
        $.ajax({
            type: "Get",
            url: '@Url.Action("AddLoadTest", "LoadTest")',
            data: { ticketNum: ticketNum, carrierId: CarrierID },
            success: function (data) {
                $('#PreviewAddLoadTest').html(data);
                $('#myAddLoadTestModal').modal({
                    closable: false,
                    transition: 'scale',
                    allowMultiple: true,
                    onDeny: function () {
                        $('#modLoadTestHide').dimmer('hide');
                        $('#myAddLoadTestModal').modal('hide');
                    },
                    onApprove: function (e) {
                        var validated = $('#frmAddLoadTest').form('validate form');
                        if (!validated) {
                            return false;
                        }
                        else {
                            $('#frmAddLoadTest').submit();
                        }
                    }
                }).modal('show');
                $('#modLoadTestHide').dimmer({ closable: false }).dimmer('show');

            }
        });
    }

    function DeleteLoadTest(loadTestId, ticketNum, CarrierID) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteLoadTest", "LoadTest")',
            data: { LoadTestID: loadTestId, ticketNum: ticketNum, carrierId: CarrierID},
            success: function (data) {
                $('#myDeleteLoadTestModal').modal('hide');
                $('#modLoadTestHide').dimmer('hide');
                $('#myLoadTestContainer').html(data);
            }
        })
    }

    function decodeHtml(html) {
        var txt = document.createElement("textarea");
        txt.innerHTML = html;
        return txt.value;
    }

    function CloseModals() {
        $('#myDeleteLoadTestModal').modal('hide');
        $('#myAddLoadTestModal').modal('hide');
        $('body').addClass('modal-open');
    };
</script>


<div class="row" id="loadtests">
    <div class="form-group col-12">
        @{
            string PSArchitect = Context.Session.GetString("PSArchitect");
            string viewType = Context.Session.GetString("ViewType");

            <label class="col-form-label"><u>Load Test Results</u></label> <a href="#" onclick="AddLoadTest('@Model.TicketNumber', '@Model.CarrierID')"><img src="~/img/indicators/add.png" height="15" width="15" /></a>

            if (Model.LoadTests.Count() > 0)
            {
                <table width="100%" border="0" class="ui striped table" style="font-size:11px">
                    <thead>
                        <tr>
                            <th>Interface Name</th>
                            <th>Burst Min</th>
                            <th>Burst Max</th>
                            <th>Burst Avg</th>
                            <th>Variance Min</th>
                            <th>Variance Max</th>
                            <th>Variance Avg</th>
                            <th>Date/Time Tested</th>
                            <th>Result</th>
                            <th></th>
                        </tr>
                    </thead>
                    @{ foreach (var loadTest in Model.LoadTests)
                        {
                            <tr>
                                <td class="info-text" height="18">@loadTest.InterfaceName</td>
                                <td class="info-text" height="18">@loadTest.Burst_Min ms</td>
                                <td class="info-text" height="18">@loadTest.Burst_Max ms</td>
                                <td class="info-text" height="18">@loadTest.Burst_Avg ms</td>
                                <td class="info-text" height="18">@loadTest.Variance_Min ms</td>
                                <td class="info-text" height="18">@loadTest.Variance_Max ms</td>
                                <td class="info-text" height="18">@loadTest.Variance_Avg ms</td>
                                <td class="info-text" height="18">@loadTest.DateTested</td>
                                <td class="info-text" height="18">
                                    @{
                                        if (loadTest.TestResult == "Pass")
                                        {
                                            @Html.Raw("<font color='green'><b>Pass</b></font>")
                                        }
                                        else if (loadTest.TestResult == "Fail")
                                        {
                                            @Html.Raw("<font color='Red'><b>Fail</b></font>")
                                        }
                                        else
                                        {
                                            @Html.Raw(" ")
                                        }
                                    }
                                </td>
                                <td class="info-text" width="20"><a href="#" onclick="DeleteLoadTestModal('@loadTest.InterfaceName', @loadTest.LoadTestID, '@loadTest.TicketNumber', '@Model.CarrierID')" style="padding:0"><img src="~/img/indicators/delete.png" height="15" width="15" /></a></td>

                            </tr>
                        }
                    }
                </table>
            } }
    </div>
</div>