SAWorkplace/Controllers/RequestController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SAWorkplace.Data;
using SAWorkplace.Models;
using SAWorkplace.Helpers;
using SAWorkplace.Constants;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.AspNetCore.SignalR;
using LoggerService;
using Newtonsoft.Json.Linq;

namespace SAWorkplace.Controllers
{
    public class RequestController : Controller
    {
        protected ApplicationDBContext aContext;
        private readonly IConfiguration _config;
        protected EmailHelper eHelper;
        protected OKTAHelper oHelper;
        private IHubContext<Services.SignalR_Notifications> _hubContext;
        private static ILoggerManager _logger;
        public RequestController(ApplicationDBContext context, IConfiguration configuration, ILoggerManager logger)
        {
            aContext = context;
            _config = configuration;
            _logger = logger;
            eHelper = new EmailHelper(context, configuration, logger);
            oHelper = new OKTAHelper(context, configuration, logger);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string viewType, string filter = "")
        {
            _logger.LogInfo("Starting Get Request Index.");
  
            HttpContext.Session.SetString("PSArchitect", "False");
            
            var userClaims = HttpContext.User.Claims;
            string oktaGroups, oktaUserName, oktaUserEmail;
            oktaGroups = oktaUserName = oktaUserEmail = string.Empty;
            
            foreach (var claim in userClaims)
            {
                if (claim.Type == "groups" && claim.Issuer == "OpenIdConnect")
                {
                    oktaGroups = claim.Value.ToUpper();
                }
                if (claim.Type == "name")
                {
                    oktaUserName = claim.Value;
                }
                if (claim.Type == "email")
                {
                    oktaUserEmail = claim.Value;
                }
            }
            HttpContext.Session.SetString("UserID", oktaUserEmail.Replace("@ipipeline.com", ""));
            HttpContext.Session.SetString("UserName", oktaUserName);
            HttpContext.Session.SetString("UserEmail", oktaUserEmail);

            string userId = HttpContext.Session.GetString("UserID");

            List<string> groupsArray = JsonConvert.DeserializeObject<List<string>>(oktaGroups);

            foreach (string group in groupsArray)
            {
                if (group == OKTAConst.architect)
                {
                    HttpContext.Session.SetString("PSArchitect", "True");
                    HttpContext.Session.SetString("AdminUser", "True");
                    break;
                }
                else if (group == OKTAConst.engageCoordinator)
                {
                    HttpContext.Session.SetString("ECUser", "True");
                    break;
                }
                else if (group == OKTAConst.sme)
                {
                    HttpContext.Session.SetString("SMEUser", "True");
                    break;
                }
                else
                {
                    HttpContext.Session.SetString("ECUser", _config["Admins:EC"].Contains(userId).ToString());
                    HttpContext.Session.SetString("AdminUser", _config["Admins:Mgr"].Contains(userId).ToString());
                    HttpContext.Session.SetString("DirUser", _config["Admins:Director"].Contains(userId).ToString());
                    HttpContext.Session.SetString("SMEUser", _config["SMEs:Ids"].Contains(userId).ToString());
                    //No break here because other OKTA groups could be included and don't want to exit the for loop too early.
                }
            }

            string PSArchitect = HttpContext.Session.GetString("PSArchitect");
            string ECUser = HttpContext.Session.GetString("ECUser");
            string AdminUser = HttpContext.Session.GetString("AdminUser");
            string DirUser = HttpContext.Session.GetString("DirUser");
            string SMEUser = HttpContext.Session.GetString("SMEUser");

            if (string.IsNullOrEmpty(viewType))
            {
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("ViewType")))
                {
                    viewType = HttpContext.Session.GetString("ViewType");
                }
                else
                {
                    if (ECUser == "True")
                        viewType = "EC";
                    else if (AdminUser == "True")
                        viewType = "Admin";
                    else if (DirUser == "True")
                        viewType = "Director";
                    else if (SMEUser == "True")
                    {
                        viewType = "SME";
                    }
                    else
                        viewType = "User";
                }
            }
            else
            {
                HttpContext.Session.SetString("FilterType", "");
            }

            HttpContext.Session.SetString("ChartFilter", filter);
            HttpContext.Session.SetString("ViewType", viewType);
            HttpContext.Session.SetString("SearchText", "");

            _logger.LogDebug("PSArchitect = " + PSArchitect + ", userId = " + userId + ", viewType = " + viewType);

            var sortType = "SORT:RequestDate_new";
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("SortType")))
            {
                sortType = HttpContext.Session.GetString("SortType");
            }
            else 
            { 
                HttpContext.Session.SetString("SortType", sortType); 
            }

            DataAccess data = new DataAccess(aContext, HttpContext.Session);

            RequestDisplayModel requestDisplay = new RequestDisplayModel();
            var filterType = "Open";
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("FilterType")))
            {
                filterType = HttpContext.Session.GetString("FilterType");
            }

            string areas = "";
            if (viewType == "SME")
            {
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("SMEAreas")))
                {
                    areas = HttpContext.Session.GetString("SMEAreas");
                }
                else
                {
                    areas = GetSMEAreas(userId);
                    HttpContext.Session.SetString("SMEAreas", areas);
                }
            }
            //filter invoked from Allocation tab - pie chart click
            requestDisplay.Requests = data.LoadRequests(userId, 0, PSArchitect, "", filterType, sortType, filter, areas);

            HttpContext.Session.SetString("FilterType", filterType);

            requestDisplay.Carriers = await data.LoadActiveCarriers();
            requestDisplay.Status = await data.GetStatuses();
            requestDisplay.Progress = await data.GetProgress();
            requestDisplay.RequestTypes = await data.GetRequestTypes();
            requestDisplay.DurationTypes = await data.GetDurationTypes();
            return View("Index", requestDisplay);
        }

        [HttpPost]
        [Route("Request/Requests")]
        public async Task<IActionResult> Requests(string filterType, string sortType = "")
        {
            //_logger.LogDebug("Starting Get Requests: filterType = " + filterType + ", sortType = " + sortType);

            DataAccess data = new DataAccess(aContext, HttpContext.Session);
            string PSArchitect = HttpContext.Session.GetString("PSArchitect");
            string userId = HttpContext.Session.GetString("UserID");
            string viewType = HttpContext.Session.GetString("ViewType");

            if (viewType != "Admin")
            {
                PSArchitect = "False";
                //HttpContext.Session.SetString("FilterType", "All");
            }
            var searchText = "";
            var chartFilter = ""; //will only use this for sort, but not if they click the filter dropdown
            if (!string.IsNullOrEmpty(filterType))
            {
                HttpContext.Session.SetString("FilterType", filterType);
                HttpContext.Session.SetString("SearchText", "");
                HttpContext.Session.SetString("ChartFilter", "");
                if (string.IsNullOrEmpty(sortType) && !string.IsNullOrEmpty(HttpContext.Session.GetString("SortType")))
                    sortType = HttpContext.Session.GetString("SortType");
            }
            else if (!string.IsNullOrEmpty(sortType))
            {
                HttpContext.Session.SetString("SortType", sortType);
                if (string.IsNullOrEmpty(filterType) && !string.IsNullOrEmpty(HttpContext.Session.GetString("FilterType")))
                    filterType = HttpContext.Session.GetString("FilterType");
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("SearchText")))
                    searchText = HttpContext.Session.GetString("SearchText");
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("ChartFilter")))
                    chartFilter = HttpContext.Session.GetString("ChartFilter");
            }
            else
            {
                if (string.IsNullOrEmpty(filterType) && !string.IsNullOrEmpty(HttpContext.Session.GetString("FilterType")))
                    filterType = HttpContext.Session.GetString("FilterType");
                if (string.IsNullOrEmpty(sortType) && !string.IsNullOrEmpty(HttpContext.Session.GetString("SortType")))
                    sortType = HttpContext.Session.GetString("SortType");
            }
            if (!string.IsNullOrEmpty(searchText))
            {

SAWorkplace/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en-us">
<head>
    <title>SME Ticket</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/lib/semanticUI/semantic.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/apple-touch-icon.png">
    <link rel="icon" id="favicon" type="image/png" sizes="16x16" href="~/img/favicon-16x16.png">
    <link rel="manifest" href="~/manifest.json" crossorigin="use-credentials">
</head>
<body style="background-color:#f7f7f7">
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/semanticUI/semantic.min.js"></script>
</body>
</html>

SAWorkplace/Views/Shared/_Layout.cshtml

@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en-us">
<head>
    <title>SA Workplace</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/lib/semanticUI/semantic.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="~/img/apple-touch-icon.png">
    <link rel="icon" id="favicon" type="image/png" sizes="16x16" href="~/img/favicon-16x16.png">
    <link rel="manifest" href="~/manifest.json" crossorigin="use-credentials">
</head>
<body style="background-color:#f7f7f7">
    <div class="ui container-fluid">
        <div class="row">
            <div class="ui large inverted pointing menu" id="topheader" style="padding:0px 10px 0px 10px">
                <a class="ui item" href="/">
                    <img src="~/img/logo.png" width="31" height="39" class="d-inline-block align-top" alt=""><span style="font-size:18px;margin-left:10px">SA Workplace</span>
                </a>
                <a id="requestTop" class="item active" asp-controller="Request" asp-action="Index">Requests</a>
                <a id="allocationTop" class="item" asp-controller="Allocation" asp-action="Index">Allocation</a>

                @if (User.Identity.IsAuthenticated)
                {
                    var userName = "";
                    var PSArchitect = "";
                    var ECUser = "";
                    var viewType = "";
                    try
                    {
                        userName = Context.Session.GetString("UserName");
                        PSArchitect = Context.Session.GetString("PSArchitect");
                        ECUser = Context.Session.GetString("ECUser");
                        viewType = Context.Session.GetString("ViewType");
                    }
                    catch { userName = "Unknown User"; PSArchitect = "False"; }
                    <div class="ui simple dropdown right aligned item">
                        @if (PSArchitect == "True" || ECUser == "True")
                        {
                            <span class="text-white"><i>(@viewType View)</i>&nbsp;</span>
                        }
                        <span style="color:gray; margin-left:8px">@userName</span>
                        <i class="dropdown icon"></i>
                        @{
                            if (PSArchitect == "True")
                            {
                                <div class="menu">
                                    <a class="item" asp-controller="Request" asp-action="Index" asp-route-viewType="Admin">Admin View</a>
                                    <a class="item" asp-controller="Request" asp-action="Index" asp-route-viewType="EC">EC View</a>
                                    <a class="item" asp-controller="Request" asp-action="Index" asp-route-viewType="User">User View</a>
                                </div>
                            }
                        }
                        @{
                            if (ECUser == "True")
                            {
                                <div class="menu">
                                    <a class="item" asp-controller="Request" asp-action="Index" asp-route-viewType="EC">EC View</a>
                                    <a class="item" asp-controller="Request" asp-action="Index" asp-route-viewType="User">User View</a>
                                </div>
                            }
                        }
                    </div>
                }
                else
                {
                    <a asp-controller="Account" asp-action="SignIn">Sign In</a>
                }
            </div>
        </div>
        @RenderBody()
        <br />
        <hr />
        <div class="ui container sub header center  aligned">
            &copy; 2020 - iPipeline SA Workplace
        </div>

        <script src="~/lib/signalr/dist/browser/signalr.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/lib/semanticUI/semantic.min.js"></script>
        <script>
            $('#topheader .mt-lg-0 a').on('click', function () {
                $('#topheader .mt-lg-0').find('li.active').removeClass('active');
                $(this).parent('li').addClass('active');
            });

            function setAllocActive() {
                $('#requestTop').removeClass('active');
                $('#allocationTop').addClass('active');
            }
        </script>
    </div>
</body>
</html>